----
- name: Configure instance(s)
  hosts: 192.168.2.40
  become: True
  gather_facts: True
  roles:
    - windows-2016-cis-benchmarks
#- hosts: localhost
#  connection: local
#  gather_facts: False

#  tasks:
#   - name: Launch the new EC2 Instance
#     ec2:
#       group: sg-0d8fc06d28b16d69c #"{{ ec2_security_group }}"
#       instance_type:  t2.micro #"{{ ec2_instance_type }}"
#       image: ami-0cc5ea3dde5301489 #"{{ ec2_ami }}"
#       wait: true 
#       region: us-east-1 #"{{ ec2_region }}"
#       keypair: AWS-TOWER-DEMO #"{{ ec2_keypair }}"
#       count: 1
#       vpc_subnet_id: 192.168.2.0/24 #"{{ ec2_vpc_subnet_id }}"
#     register: ec2

#  tasks:
#    - name: Update all packages to latest
#      yum: name=* state=latest#
#
#    - name: Install specific nginx package for centos 7
#      yum: name='http://nginx.org/packages/centos/7/noarch/RPMS/nginx-\release-centos-7-0.el7.ngx.noarch.rpm' state=present

#- ec2_ip_address: 192.168.2.136
#    win_ec2_name_prefix: example
#  roles:
#    - role: windows-2016-cis-benchmarks
  
  
#- name: Configure instance(s)
#  hosts: 192.168.2.136
#  become: True
#  gather_facts: True
#  roles:
#    - role: windows-2016-cis-benchmarks
  
#- name: Harden Server
#  hosts: all
#  roles:
#    - role: windows-2016-cis-benchmarks

##############PLaybook notes#############


###########Creates inventory of new server in memory#############
#- hosts: localhost
#  connection: local
#  tasks:

#    - name: make inventory win
#      add_host:
#        name: "{{ target }}"
#        ansible_host: "{{ ansible_inv_host }}"
#        ansible_user: Administrator
#        ansible_ssh_pass: "{{ win_pass }}"
#        ansible_connection: winrm
#        ansible_port: 5986
#        ansible_winrm_server_cert_validation: ignore
#        ansible_winrm_operation_timeout_sec: 100
#        ansible_winrm_read_timeout_sec: 120
#      when: os == "windows"

#    - name: wait for winrm
#      wait_for:
#        port: 5986
#        host: "{{ ansible_inv_host }}"
#        timeout: 600
#      when: os == "windows"
      
#- hosts: '{{ target }}'
#  vars:
#    root_password: "{{ win_pass }}"        


#  roles: 
#    - role: windows-2016-cis-benchmarks



  
############Example working in rehel and CentOS######
#    - name: make inventory
#      add_host:
#       name: "{{ target }}"
#       with_items: 
#       - "{{ ansible_distribution }}"
#       ansible_host: '10.5.32.203'
#       ansible_become: true
#       ansible_user: root
#      when: os == "RedHat" #"7.8"   
      
#- hosts:  "{{ target }}"
#  become: true
#  vars:
#    - ansible_ssh_user: rotero1 
#    - ansible_ssh_pass: rotero1.1
#  when: os == "redhat" 
############Example working in rehel and CentOS######   
